export const ErrorTypes = {
  "tenant.not_exist": "El inquilino no existe",
  "tenant.already_exists": "El inquilino ya existe",
  "tenant.has_users": "El inquilino tiene usuarios",
  "user.not_exist": "El usuario no existe",
  "user.already_exists": "El usuario ya existe",
  "user.invalid_credentials": "Credenciales inválidas",
  "user.invalid_current_password": "Contraseña actual inválida",
  "user.inactive_user": "Usuario inactivo",
  "budget.not_exist": "El presupuesto no existe",
  "budget.has_concepts": "El presupuesto tiene conceptos",
  "concept.not_exist": "El concepto no existe",
  "concept.already_exists": "El concepto ya existe",
  "concept.has_engagements": "El concepto tiene compromisos",
  "concept.parent_is_in_another_concept_group": "El padre está en otra agrupación",
  "concept.sub_concept_is_in_another_concept_group": "El subconcepto está en otra agrupación",
  "concept_group.not_exist": "La agrupación no existe",
  "concept_group.already_exists": "La agrupación ya existe",
  "concept_group.has_concepts": "La agrupación tiene conceptos",
  "engagement.not_exist": "El compromiso no existe",
  "engagement.already_exists": "El compromiso ya existe",
  "engagement.concept_not_found": "El concepto no existe",
  "engagement.assigned_engagement_already_exists": "Ya existe un compromiso asignado",
  "engagement.already_assigned": "El compromiso ya está asignado",
  "engagement.is_not_assigned": "El compromiso no está asignado",
  "engagement.parent_concept_already_assigned": "El concepto padre ya está asignado",
  "engagement.parent_concept_is_in_concept_group": "El concepto padre está en otra agrupación",
  "project.not_exist": "El proyecto no existe",
  "project.already_exists": "El proyecto ya existe",
  "project.has_budget": "El proyecto tiene presupuesto",
  "project.has_concepts": "El proyecto tiene conceptos",
  "project.image_too_large": "La imagen no puede ser mayor a 2MB",
  "template.not_exist": "La plantilla no existe",
  "template.already_exists": "La plantilla ya existe",
  "industrial.not_exist": "El industrial no existe",
  "industrial.already_exists": "El industrial ya existe",
  "industrial.has_engagements": "El industrial tiene compromisos",
};
